/*
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNODOZZOZOOONMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNDNMD8OO$8O7ZDMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMDDDMMNDD$78$??$DMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM8IZOI=+I8MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNZIZO?+IIZMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNMMMMMMNMM$7$7II77DMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMOONMMMMMMMMM8$7$7Z$DMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMZ$ONMMMMMMMMMMO?I?Z8NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNIO8DDNNMMMMMMM8?++8DNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMD$$O8DDNMMMMMMND?=I8DNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMOIINO88DNMMMMMMOI+O88DMMNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMD8O7$DZOZO8DNMMMM7?IOOONMNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNDD88OZZO8Z$$ZZODNMNDI+7ZZODMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMD$$$ZZZZO8OOZ$Z$ZZOD8Z+=$OO88MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM8O7I7$$7ZND7OOZ?+?++??+~IZO88ODMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMZ$I777IIOO7???+==~::===I$ZOOOZONMMNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNZ$II77I8$7?+===~::~=++?$ZZOZ$$Z8NN8$DMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN87IIII8O7??+~===+++++?7ZOOOO7?I$ZOZ+I8MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMDI???IO$???II7$Z$77777$$ZOOOI+$O88O++IODMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNZ7???IOI??III$$ZOOOOOZ$IZOOZ?$DDD88I??IIOMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNI$NMMMMMMMMMMMMDO77???$I?I????7$Z8DDDDZ?ZOOOO+DNND8OI????IDMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO+?8MMMMMMMMMMMNO7II?+I$$I?++=+I7ZO8NDOI$$ZO8ZIDMMNDO??I???OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMZ?+?ZDMMMMMMMMMDO$II??7$ZZ7+++++I7$$$ZZ$II??7Z7ZODNND7+II++?NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN~~:=?IDMMMMNNNDII?II7ZZZOO7=~~==++???II??++==+?III$Z?=II?=+NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM+~~~~+7NMMMMD88$II$7I7ZZZ$===~+??II?????+++=~~=+??II+I77?=$MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN?+==+7ZMMNDD88OZI7$I?I77I===+~++7ZOOOOZ7++I++++II??+I$$+=?NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM8I?++I$NNND88OO87II?????+=+I+??+=+IO888OZIZNDII777??????=~NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM$7?777ZODDZOD7?++++I7?++?~77????++?$OOOZ$$8NMD$777II7I?=~~DMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMIIIIZ$77I??++=++??III+++~=I?+?+=+?7$OZ$$OZO8NNNNIII??++===OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO+I7I8ZZ$7III?=+I7Z$I~=I==~~~===+I$ZZZ$OOOO8NMMMMNNMNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN++77$O$$ZOOZZI=+I$Z8::~~=+++??+?7$ZZZZZO8DNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN?I7$8NDOZZ$$7+==~::,,,=77IIII??I7ZOZ$$O8DNNNNMNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNZ7Z8O8NMNNNNNDD+~:,,,:?????IIIII$Z$$Z8ODNNNNNMNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOZ8D8ONNMMMMNNI==:::~+=+?????II7$$$OOOODNNNNMMNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN8DMMNNMMMMNNNN7?+::?==???+IIII7$7OZOZDNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNMNNNDDNN$?~=?:==?+???7II$OO$DNNNNNNNNNMMMMMMMMMMMMMMMNMMN88DDNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNDN8$II=7~+:+=++?77IZOO$ZOOZO8DDNNMMMMMMMMMMMMMN$III?IIII7$ODNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNMDZZ$$7I?I?=:~===?77$ZOZIII?==~~~=+NMMMMMMMMMNZI777II?I7I?+IZZ8NMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNN8O$II??+?+++=I=~~++???I+=~=~:+I?=:=DMMMMMM8I7$???++I7I777$777ZDNMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNND8I?==+=++?I+OI~:==+??I+~~~+:=~::::?I7Z8DD?II?II+=+I7III7$$ZZZ8NMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNN??ZZZ$??I??I?=:::=?++==~~=~~~====~+III???IIIII+=?IIIIII7ZO8DDNMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNN8IZOO$+=~=++~~:~::==+++===~:=+=====~~~~==~~~~~+?I??I7$$ZOO8D8NMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNMNNN8ZOZ+~=~===::::::~=?+?++==~~IIII?+===+??++I7II?+?87IZOOOOO8NMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNDD8D8I?++===~=~,,,=+7I+++I?=~=+I7$77?+?I++?7$+=?O8O?+?7$ZZZONNMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNDOOZZOO$I7I78OI+=::~I77?++I7I~~~=+I7I?III?++?788888OZ7III77ZODNMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN$ZZO$887IZI$87++I=::+$Z7????7?~:~~:~??7$$7II7$O8888ZO$?7$I7I$ONMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMND$INOIOD7ZZ$Z8$?I?+~,,7$II?+???====+~~=?I7$$777$OOOZII?7$$7I7$8DMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMND8OI7ON$7878ZOOZ7I$7=:,.:II?++??==+==~=+==?7ZOZ777ZZ7I?I7OO$OO$O88NMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN8ZOO$77ONDZZ7ZOOZZZ?I=:,,,,~???+?=++=~+?+~:=IIZ8OZOOZ777=7OO8NDOD8O88DMMMMMM88NNMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMND8ODNND8N8$777$Z$OZOOZZ7$ZZ8DD8$=~:,,:~=~~~?II?++?????$?I$Z7ZZ$??+=IZO8DNDDOZZZZNMMNNDZZNMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNZ++8O$$$77I????III7OOZ88OZ7O8DDD8?~?=+~?==??III?+++I???7I7II7O$I???7$$ZZOOOO$$ZZZ88OOOZ$8NNNMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMNMMMMMMMMMMNNI=+ONNND7????????II$8DD8Z8DNDDD87:+??III+?+??III++????II?I7Z$?I7$Z77$7777$$ZOOZOOOZZ$$$$8$ZNMMMMMMMMMMMMMMM
MMMMMMMMMNND88O8MMMMONMMMMMMMMMNNNO?=?8DNN$?+IIII??+8DD8ODNDDDD8O?~~+=+??++=+++I?~~+=+??I77II?+?IIII7$77II$ZOZ$ZZ$7$7I77$ZO88MMMMMMNMNNMMMMM
MMMMMMMMO8NNO$$ZOOO8ODNMMMMMMMNDNNDOI?II$$II?I77I?+I88D87DD8DDD88?+?~:=??=~:~+===::==~=+III?7I?7II?+=IIII77$$7777777II77ZZODNNNMMMNNM$ZMMMMM
MMMMMMMMMMMMND7D8OZ$7Z8NMMMMMMNODN8ONND$I??II77$7I+?8OO$8D8888D88?+?~=?7I+::=+====~=:~~=+?+77I?I7I???+?I???I$I7IIIII7ZZOOZ8NNNMMMMND$+?ODMMM
MMMMMMMMMMMMMNZOIZO7I$ZDMMMMMMN77DO$NNNN8II?I7$$7I??8$ZZDDD8888OOI==++$Z7I:,=?++?I?+=~~~+??$77II777III????III77III7I888OO8NNMMMNMMNZZ7?7DMMM
MMMMMMMMMMMN8ZI7?$7??I78MMMMMMN??$I?O88O7??+?77I$7?$O?ZOO888O88Z$7+?I?Z$7?~==+?+7I+=~~~~=+77777I7$777$7+?II?IIII7Z7D88DO?DNNNN:,=8OOO8I~8DMM
MMMMMMMMMMMOZ$I?I7II?+?ZNNNNMNNI+=~II?IIII==?I7I+77$I?7O8DDD88ZI?7??77$7II=?=?+?Z7I+==+I777777$7I7III77++I???III$$DDN?I?ODDDDN,?$?+$8+.,8DNM
MMMMMMMM8DNZZ$I?7I?7?+?78DNNMND++=:=7??78Z+=+I77+$O=+?I78DZDZI?++I?IIZZ$I+=IIII7$777I????II7$Z$7II??III++=++I77$IZODDO?I$OI88DZIZZ7Z8,.~8O~8
MMMMMMD?+++??+I7I??II+?II?IZ8$+?7===??I7Z?=~=?I77$$=?I$Z$I7ZZZ7II??7ZOZ$7=~7I?7$7II???==?II7$Z$$7I???II?=::~?77$ZZOO88??7??+?7ZZO8DNNO=+I+~I
MMMMMMN7?I?+?I7?++?II?++?III+~~??O+?I=+??+++?I$ZOZ?I$ZZZZZOZZZ$+=+I$$ZZ7$?:=++++?I7??I??7I7$ZZZ$7I?II77=+~~~~=?ZZOZZZZ+7Z$II?7$O8DDNNDD8$ID8
MMMMMMM$??+?I77I?++=+====+I7+=~=+77?77O8D88OOZOZ7$ZOZ7$$77O$IIZ+~+I$ZZ777~~?77I??IIIIII?III7$$777III++~~=~~+~~=?OOO$Z=IZZ$$7?OZ8NMMDN8ZIO888
MMMMMMMN??7OIIIII+=~==:=~+?+~~+++?7$??ZDDD8888DDDDDDD8DNNNDDZI?~=7III+?~:=7I7III??I77I?+??I7III+=+????=~~~:=IO8$$$$7??7$7I7O8ONMMMMMMND8Z8MM
MMMMMMMN8IIII???+==~~==~~===:~+I77$ZOOD888888888DD8DDDNNNDDD+:==?Z7~~~~?I7I7II?++II77I+??I$$7II?77IIII+==~~~I7Z7$7+?I?I?OO8DOZMMMMMMMDNDNMMM
MMMMMMNMND$?++??=~~~~~~=~~~:::?8DD88DDDD88D888DDDDD8DDNNDDD::I7?+$7+Z?+$$IIII?I7I??$7I?+I7$$$7I$Z$I??++??=~~=????II?I7O88DNNDMMMMMMMDNMMMMMM
MMMMMMMMMMMDI?==~::~~=+??II=::7ZODDND88DDDDD888DD8DDDDNND8$~7O87+ZZ7Z??7$7III=+$?+?II7+??I7$7$$ZZ$?IIII?+=~=:=??II?I$Z888NMNNNMMMMMMMMMMMMMM
MMMMMMMMMMMM8??=~:~~=????I??~~IIIDNDD88DDDD8888DD88DDDDDO7?O88DZ??~=7?I777$$???I=+??+I??IIIII?$Z7?I77II?=~7+==?77II7OZDODMMNDDMMMMMMMMMMMD8N
*/

#include "OSG_PhysX_test.h"




void COSGPhysXTest::init(NxScene* scene)
{

	//NxScene* scene, osg::Vec3f size, osg::Vec3f position
	
	osg::Vec3f size;
	size.set(1,1,1);

	osg::Vec3f position;
	position.set(1,1,1);

	osg::Group* group = new osg::Group;
	p_cube = new CPhysXCube(scene, size, position );
	//group->addChild(p_cube);		
}




void COSGPhysXTest::render(void)
{

	//CPhysXCube cube_alpha;
}


void COSGPhysXTest::destroy(void)
{
	delete p_cube;

}