
/*
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNMO88NMMMMN$NNMMNNNDOZMMMMMMMMNNNNMMMMMMMMMMNMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMDNOO8MMMN7DNNMMNDDMO8MMMMMMMMNNNNMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMDNDO8MM7ONNMMNNDDNO8DMMMMMMMNNNNMMMMMMMMMNMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMDD7N$8DNNNMNNDM8$DNMMMMMMMNNNMNMMMMMMMMNMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM877DDNNNNN8NM8$NDNMMMMMMMNNNNMMMMMMMMNMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM7ODDNNNNNNMM8ZNDMNMMMMMMNMMNMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMODOONNNDONMNZODDNMNMMMMMMNNNMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM88DNNDNN8NMMO$ODDNMMMMMMMMNNNMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM$DDNNNODDNNMO$ODDNMMNMMMMMNNNMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMZDDNNNNNDNNMOZ8DDNNMMNMMMMNNNMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM78DNNNNNNNDNNZZD8DNNMMMNMMMMNNMMMMMMMMNMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMODDNNNNNNNMM$$7NDDDNMMMMNMMMNNMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM$DDNNNNNNNNMMZ$IDDD8NMMMMMNMMNNMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMI8DNNNNNNMNMMDZ$$NN88NNMMMMMNMMNMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM88DNNNNNNMNNNM$Z$ZNMD8NNMMMMMNNMNMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMODDNNNNNNNNNNM$$$ONMD8NMNNNMMNNDNMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM8DNNNNNMNMNNNNZ$$8NM88NMMMNNNNNNDMMMMMMMMMNMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM8DNNNNNNNMNNN8Z$ZDNM8DNMMMMMMNNNNDMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM8DNNNNMNMMMND$$$7NMNDMDMMMMMMMMNDNDMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM8DNNNNMNMMMDDZ$$7NMN8NMMMMMMMMMNNNNMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMZDNNNNMNNMND7$7ZDMM8DNNMMMMMMMMNNMMDMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM8DNNNNNMMDN$$$7NNNZNMMMMMMMMMMMMMMM8MMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMZDDNNNNMDN$$7ZDNNNNDMMMNMMMMMMMMMMMMNMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM8DDNNNDD8$7$8DNNO8MMMNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM8DDNNDDD$$$IDNNN8MMMMNNMMMMMMMMMMMMMNMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMDDDMMMMMMMMMMMMMMMMMMMMMMMMD8DDDD8D7$$7DDNDZMMMM8NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM8888OOOOOO78MMMMMMMMMMMMMMMMMMMODDDDOD7$$$N8DD8DMMM8DNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM8+:O8$=I$ZOOO8O$+MMMMMMMMMMMMMM8O8DDDOOI$$7D88D8OMMMDDNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO=8DDNN?777$O88888O7,NDDDDDDDD$ZZO88Z$O?7$ZDDD88NMMM8NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM,O8DDNNZZZOOOZZO8D888Z?:~=+~=I7$$III7OI77$8DDOOMMMMMNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN,O8DNNNIOO888888OOO8888O$I77?==+?I+++==+88DMMMMMMMM8NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMI,?77II+?III7$O8888888888O+====+?+??++=?7DNDNMMMMMDNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMD87+I7+I7$$$$77II$Z88888$77?~:=7+II+=+??77DNDNMMMNDNMMMMMMMMMMMMMMMMMMMMMMNMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMDDD$?I7$$ZZZ$$$77III$Z$$?==~~????~~+??I$$ZNNNNMMNDNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMOZO8$I77777777777I?+~~=+==~++==~=I$7$7$$$NMMNDNNDNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM8ZO8888OO88888Z7I++??I777777I+++=~~:=++?I==?I$8Z77?NNMMMNNDDNMMMMMMMMMMMMMMMMMMMNMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMDDDDDDDDD8888OOI????II??I7$$$$7+??++=+?==++~:~7?OO$I=DNMMMMNNN8DNMMMMMMMMMMMMMMMMMNMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMDD?,,..:?7ZZOO$?++?+++?I7$7I77$??I?+=+$7$?I+=:::~=OZ?7NNNNMMMNNNDD8NMMMMMMMMMMMMMMNNMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMND====,~=???+~==++?===?I7$ZOZ7I+???+=7$ZZZ?787:::~7$I8NDNNNNMNNNNNDNN8NMMMMMMMMMMNNMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMND~+=+ZZ=7$ZZZZ++=~,:+I$ZZ$$$Z7??+==+$ZOZOZ?O88I~IO$ZDDDNNNNNNNNNNNNDNNN8NMMMMMMMNDMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO.~~$8D~I7I7ZZ?~~~::I7II$OZ$7++?+=?OZOZZZOZZZZOZZO8NDDDDDNNNNNNNNNNNNDNNNDDMNMMMMNMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM8.:IO=I77$$?~~::~~:I$$ZZ7?77=++=+OZ8DDNNNNDDDNNNNNNNNNDDDDNNNNNNNNNNNNNNNNDDDNNNNDMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO,::~====+=,=+~~=~+ZO8877I==++$OZODDDNNNNNNMMMMMMNNNNNNDDDDNNNNNNNNNNNDDNNNNDDNNNDMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMZ7~+~=+++=,.~~:~=~77I?+?~=+I?7ZODD8DDNNNNNNMMMMMMMMMNNNNDDDNNNNNNNNNNNNNNNNNN8DDNDMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMDO,~=++++=.==,:~:==+++?$OOOOOZ78DNNDDDNNNNNNMMMMMMMMMMNNDONNMMMMMMMMMMNNNDDNNNODDDMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM,=+~~=+==:,+::~~+I7$$ZOOOOO8DND$$DNMMNDDNNNNNMMMMMMMMMMMNONMMMMMMMMMMMMNNNNDDDDO8MMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM:::~+=:~:~~,=:~~~I$$ZZZZZODNNNNNDOZ8MMMMNNNNNNMMMMMMMMMMMMD8MMMMMMMMMMMMNNNNNDD8OMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.,..,,:~=~~~,,~~=I777$Z8DNNNNNNNNND88ODMMMMMNNNNMMMMMMMMMMMNNDNMMMMMMMMMNNNNNDD88MMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM,:=?7.~~=+??+,,~~7ZO88DDDDNNNNNNNNNNDDD88MMMMMNNNNNNMMMMMMMMMNNNNMMMMMMMMDDDDDOMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.~?I$,~=????+,.?$O88DDDDNNNNNNNNNMMMNDDDD8DMNMNNNNNNNNMMMMMMMMNNNNMMMMMNO88ZMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM:~+I$,~+?III,,,Z88DDDDDDNNNNNNNNMMMMMNDDNDD8DNNNNNNNNNNMMMMMMMMNMMNMMD$77MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM,:+I.=+??=.~~,8DDDDDDDDNNNNNNNMMMMMMMNDNDDDD8DNNNNNNNDD8MMMMMMMNNNNI=+$MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM$:.,::,:==+~=DDNNNNDDNNNNNNNNMMMMMMMMNDDDDDDDDDNNNMNNNNDOZNMMM8Z===7ONMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM,::~~=+I7?~ONNNNNNNNNNNNNNNNMMMMMMMMMN8888DDDDDNNMMMMNNNND8Z7?+?IIZDMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.:=+I7$$$I?=,NNNNNNNNNNNNNNNNNNMMMMMMMMM8$OO8DDDNNDDNMMMMMDD8Z$7?$ZOZMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMM~,~=+?I$$7I?+~ZNNNNNMMMMMMNNNNNNNMMMMMMNND8ZZZ8DDNNNNNNDDDNNZOO8Z7ZO8OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMM.:~++?I77I?+==:NNNNMMMMMMMMMMMNNNNNMMNNNNNDD8ZOOO8DNNNNNDMMN$88888D8ZDMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMO.:~=+?III?+=~~:NNNNNMMMMMMMMMMMMMMMNNDDNNNNND8ZZ8DDOZO8DNNO$O8D8NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMM.,~==????+=~:~ZDNNNNMMMMMMMMMMMMMMMMMDDDDDNNNNDOZ8DNND88OOOO8DNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMM.:~==+++==:.=NDNNNNNMMMMMMMMMMMMMMMMMNDDDDDDNNNN8ZODDDNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMM.:~=+??++=~=DNDNNNNNNMMMMMMMMMMMMMMMMNDDNDDDDDDNDDO$8DMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMM.:=+?II??+~ZDNNNNNNNNMMMMMMMMMMMMMMMMMDDDNNNNND8O88OIOMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMM,~=+?III?=~DDNNNNNNNNMMMMMMMMMMMMMMMMMNDDDDNNDD88NM87NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMM,~=+?III?==NNNNNNNNNMMMMMMMMMMMMMMMMMMMDDDDDDD8MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMM,:=+?II?+~ZDNNNNNNNMMMMMMMMMMMMMMMMMMMMDDDDD88MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMM:~=+??I?=~DDNNNNNNNMMMMMMMMMMMMMMMMMMMMDD888OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMZ,~=+???+~7DDDNNNNNMMMMMMMMMMMMNNNNNNNNND88OZ8MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMM:~=+???~=DDDNNNNNNNMMMMMMMMNMMMMNNNNNNND8OZZMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
*/
/* Static actor - CPlane - Janusz Goldasz */
#include "Plane.h"

void CPlane::init()
{
	NxPlaneShapeDesc PlaneDesc;
	PlaneDesc.d = 0.0;
    NxActorDesc actorDesc;
    actorDesc.shapes.pushBack(&PlaneDesc);
    NxActor* _CPlaneActor = _scene->createActor(actorDesc);	
	_CPlaneActor->setName(this->getName().c_str());
}

osg::Geode* CPlane::createQuadGeometry(osg::Vec3f origin, float size, bool flip)
{
	_geode = new osg::Geode;

	bool xyCPlane = true;

	osg::Geometry* _quad = osg::createTexturedQuadGeometry(_origin - osg::Vec3f(0.5f*size,0.5f*size, 0),
		osg::Vec3(size,0.0f,0.0f),
		xyCPlane ? osg::Vec3(0.0f,size,0.0f) : osg::Vec3(0.0f,0.0f,size),
		0.0f, flip ? 1.0f : 0.0f , 1.0f, flip ? 0.0f : 1.0f);

	std::string filename = 
		"../images/grid2.png";
	osg::Image* image = osgDB::readImageFile(filename);
	
	osg::Texture2D* texture = new osg::Texture2D(image);
    texture->setFilter(osg::Texture::MIN_FILTER,osg::Texture::LINEAR);
	texture->setWrap(osg::Texture::WRAP_S, osg::Texture::CLAMP_TO_BORDER);
    texture->setWrap(osg::Texture::WRAP_T, osg::Texture::CLAMP_TO_BORDER);

	_quad->getOrCreateStateSet()->setTextureAttributeAndModes(0,
		texture,
		osg::StateAttribute::ON);
	_quad->getOrCreateStateSet()->setMode(GL_BLEND,osg::StateAttribute::ON);
    _quad->getOrCreateStateSet()->setRenderingHint(osg::StateSet::TRANSPARENT_BIN);
	_geode->addDrawable(_quad);
	_geode->setName(this->getName().c_str());
	return _geode;
}